window.esdocSearchIndex = [
  [
    "id-builder/src/tasks/babelcodecompiletask.js~babelcodecompiletask",
    "class/src/tasks/BabelCodeCompileTask.js~BabelCodeCompileTask.html",
    "<span>BabelCodeCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/BabelCodeCompileTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/compilers/babelcodecompiler.js~babelcodecompiler",
    "class/src/compilers/BabelCodeCompiler.js~BabelCodeCompiler.html",
    "<span>BabelCodeCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/BabelCodeCompiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/compilers/coffeescriptcompiler.js~babelcodecompiler",
    "class/src/compilers/CoffeeScriptCompiler.js~BabelCodeCompiler.html",
    "<span>BabelCodeCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/CoffeeScriptCompiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/compilers/babelmapcompiler.js~babelmapcompiler",
    "class/src/compilers/BabelMapCompiler.js~BabelMapCompiler.html",
    "<span>BabelMapCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/BabelMapCompiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/browsersyncservertask.js~browsersyncservertask",
    "class/src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask.html",
    "<span>BrowserSyncServerTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/BrowserSyncServerTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/browserifycompiletask.js~browserifycompiletask",
    "class/src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask.html",
    "<span>BrowserifyCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/BrowserifyCompileTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/compilers/browserifycompiler.js~browserifycompiler",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html",
    "<span>BrowserifyCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/BrowserifyCompiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/lib/builder.js~builder",
    "class/src/lib/Builder.js~Builder.html",
    "<span>Builder</span> <span class=\"search-result-import-path\">id-builder/src/lib/Builder.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/coffeescriptcompiletask.js~coffeescriptcompiletask",
    "class/src/tasks/CoffeeScriptCompileTask.js~CoffeeScriptCompileTask.html",
    "<span>CoffeeScriptCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/CoffeeScriptCompileTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/lib/compiletask.js~compiletask",
    "class/src/lib/CompileTask.js~CompileTask.html",
    "<span>CompileTask</span> <span class=\"search-result-import-path\">id-builder/src/lib/CompileTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/lib/compiler.js~compiler",
    "class/src/lib/Compiler.js~Compiler.html",
    "<span>Compiler</span> <span class=\"search-result-import-path\">id-builder/src/lib/Compiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/copycompiletask.js~copycompiletask",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html",
    "<span>CopyCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/CopyCompileTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/compilers/copycompiler.js~copycompiler",
    "class/src/compilers/CopyCompiler.js~CopyCompiler.html",
    "<span>CopyCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/CopyCompiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/directorycleanertask.js~directorycleanertask",
    "class/src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask.html",
    "<span>DirectoryCleanerTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/DirectoryCleanerTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/lesscompiletask.js~lesscompiletask",
    "class/src/tasks/LessCompileTask.js~LessCompileTask.html",
    "<span>LessCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/LessCompileTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/compilers/lesscompiler.js~lesscompiler",
    "class/src/compilers/LessCompiler.js~LessCompiler.html",
    "<span>LessCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/LessCompiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/livescriptcompiletask.js~livescriptcompiletask",
    "class/src/tasks/LiveScriptCompileTask.js~LiveScriptCompileTask.html",
    "<span>LiveScriptCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/LiveScriptCompileTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/compilers/livescriptcompiler.js~livescriptcompiler",
    "class/src/compilers/LiveScriptCompiler.js~LiveScriptCompiler.html",
    "<span>LiveScriptCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/LiveScriptCompiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/_plantumlcompile.js~plantumlcompile",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html",
    "<span>PlantUMLCompile</span> <span class=\"search-result-import-path\">id-builder/src/tasks/_PlantUMLCompile.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/servertask.js~servertask",
    "class/src/tasks/ServerTask.js~ServerTask.html",
    "<span>ServerTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/ServerTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/styluscompiletask.js~styluscompiletask",
    "class/src/tasks/StylusCompileTask.js~StylusCompileTask.html",
    "<span>StylusCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/StylusCompileTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/compilers/styluscompiler.js~styluscompiler",
    "class/src/compilers/StylusCompiler.js~StylusCompiler.html",
    "<span>StylusCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/StylusCompiler.js</span>",
    "class"
  ],
  [
    "id-builder/src/lib/task.js~task",
    "class/src/lib/Task.js~Task.html",
    "<span>Task</span> <span class=\"search-result-import-path\">id-builder/src/lib/Task.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/testtask.js~testtask",
    "class/src/tasks/TestTask.js~TestTask.html",
    "<span>TestTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/TestTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/watchtask.js~watchtask",
    "class/src/tasks/WatchTask.js~WatchTask.html",
    "<span>WatchTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/WatchTask.js</span>",
    "class"
  ],
  [
    "id-builder/src/tasks/babelcodecompiletask.js~babelcodecompiletask",
    "variable/index.html#static-variable-babelCodeCompileTask",
    "<span>babelCodeCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/BabelCodeCompileTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/compilers/babelcodecompiler.js~babelcodecompiler",
    "variable/index.html#static-variable-babelCodeCompiler",
    "<span>babelCodeCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/BabelCodeCompiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/compilers/coffeescriptcompiler.js~babelcodecompiler",
    "variable/index.html#static-variable-babelCodeCompiler",
    "<span>babelCodeCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/CoffeeScriptCompiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/compilers/babelmapcompiler.js~babelmapcompiler",
    "variable/index.html#static-variable-babelMapCompiler",
    "<span>babelMapCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/BabelMapCompiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/browsersyncservertask.js~browsersyncservertask",
    "variable/index.html#static-variable-browserSyncServerTask",
    "<span>browserSyncServerTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/BrowserSyncServerTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/browserifycompiletask.js~browserifycompiletask",
    "variable/index.html#static-variable-browserifyCompileTask",
    "<span>browserifyCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/BrowserifyCompileTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/compilers/browserifycompiler.js~browserifycompiler",
    "variable/index.html#static-variable-browserifyCompiler",
    "<span>browserifyCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/BrowserifyCompiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/lib/builder.js~builder",
    "variable/index.html#static-variable-builder",
    "<span>builder</span> <span class=\"search-result-import-path\">id-builder/src/lib/Builder.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/coffeescriptcompiletask.js~coffeescriptcompiletask",
    "variable/index.html#static-variable-coffeeScriptCompileTask",
    "<span>coffeeScriptCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/CoffeeScriptCompileTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/lib/compiletask.js~compiletask",
    "variable/index.html#static-variable-compileTask",
    "<span>compileTask</span> <span class=\"search-result-import-path\">id-builder/src/lib/CompileTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/lib/compiler.js~compiler",
    "variable/index.html#static-variable-compiler",
    "<span>compiler</span> <span class=\"search-result-import-path\">id-builder/src/lib/Compiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/copycompiletask.js~copycompiletask",
    "variable/index.html#static-variable-copyCompileTask",
    "<span>copyCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/CopyCompileTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/compilers/copycompiler.js~copycompiler",
    "variable/index.html#static-variable-copyCompiler",
    "<span>copyCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/CopyCompiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/directorycleanertask.js~directorycleanertask",
    "variable/index.html#static-variable-directoryCleanerTask",
    "<span>directoryCleanerTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/DirectoryCleanerTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/lib/getfiles.js~getfiles",
    "function/index.html#static-function-getFiles",
    "<span>getFiles</span> <span class=\"search-result-import-path\">id-builder/src/lib/getFiles.js</span>",
    "function"
  ],
  [
    "id-builder/src/index.js~index",
    "function/index.html#static-function-index",
    "<span>index</span> <span class=\"search-result-import-path\">id-builder/src/index.js</span>",
    "function"
  ],
  [
    "id-builder/src/tasks/lesscompiletask.js~lesscompiletask",
    "variable/index.html#static-variable-lessCompileTask",
    "<span>lessCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/LessCompileTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/compilers/lesscompiler.js~lesscompiler",
    "variable/index.html#static-variable-lessCompiler",
    "<span>lessCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/LessCompiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/livescriptcompiletask.js~livescriptcompiletask",
    "variable/index.html#static-variable-liveScriptCompileTask",
    "<span>liveScriptCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/LiveScriptCompileTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/compilers/livescriptcompiler.js~livescriptcompiler",
    "variable/index.html#static-variable-liveScriptCompiler",
    "<span>liveScriptCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/LiveScriptCompiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/lib/parseoptions.js~parseoptions",
    "function/index.html#static-function-parseOptions",
    "<span>parseOptions</span> <span class=\"search-result-import-path\">id-builder/src/lib/parseOptions.js</span>",
    "function"
  ],
  [
    "id-builder/src/tasks/_plantumlcompile.js~plantumlcompile",
    "variable/index.html#static-variable-plantUMLCompile",
    "<span>plantUMLCompile</span> <span class=\"search-result-import-path\">id-builder/src/tasks/_PlantUMLCompile.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/servertask.js~servertask",
    "variable/index.html#static-variable-serverTask",
    "<span>serverTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/ServerTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/styluscompiletask.js~styluscompiletask",
    "variable/index.html#static-variable-stylusCompileTask",
    "<span>stylusCompileTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/StylusCompileTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/compilers/styluscompiler.js~styluscompiler",
    "variable/index.html#static-variable-stylusCompiler",
    "<span>stylusCompiler</span> <span class=\"search-result-import-path\">id-builder/src/compilers/StylusCompiler.js</span>",
    "variable"
  ],
  [
    "id-builder/src/lib/task.js~task",
    "variable/index.html#static-variable-task",
    "<span>task</span> <span class=\"search-result-import-path\">id-builder/src/lib/Task.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/testtask.js~testtask",
    "variable/index.html#static-variable-testTask",
    "<span>testTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/TestTask.js</span>",
    "variable"
  ],
  [
    "id-builder/src/tasks/watchtask.js~watchtask",
    "variable/index.html#static-variable-watchTask",
    "<span>watchTask</span> <span class=\"search-result-import-path\">id-builder/src/tasks/WatchTask.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/compilers/babelcodecompiler.js",
    "file/src/compilers/BabelCodeCompiler.js.html",
    "src/compilers/BabelCodeCompiler.js",
    "file"
  ],
  [
    "src/compilers/babelcodecompiler.js~babelcodecompiler#compilechunk",
    "class/src/compilers/BabelCodeCompiler.js~BabelCodeCompiler.html#instance-method-compileChunk",
    "src/compilers/BabelCodeCompiler.js~BabelCodeCompiler#compileChunk",
    "method"
  ],
  [
    "src/compilers/babelmapcompiler.js",
    "file/src/compilers/BabelMapCompiler.js.html",
    "src/compilers/BabelMapCompiler.js",
    "file"
  ],
  [
    "src/compilers/babelmapcompiler.js~babelmapcompiler#compilechunk",
    "class/src/compilers/BabelMapCompiler.js~BabelMapCompiler.html#instance-method-compileChunk",
    "src/compilers/BabelMapCompiler.js~BabelMapCompiler#compileChunk",
    "method"
  ],
  [
    "src/compilers/browserifycompiler.js",
    "file/src/compilers/BrowserifyCompiler.js.html",
    "src/compilers/BrowserifyCompiler.js",
    "file"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#adddependency",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-method-addDependency",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#addDependency",
    "method"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#bundle",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-member-bundle",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#bundle",
    "member"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#bundledependencies",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-member-bundleDependencies",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#bundleDependencies",
    "member"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#compilechunk",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-method-compileChunk",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#compileChunk",
    "method"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#constructor",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-constructor-constructor",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#constructor",
    "method"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#handlebundledependency",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-method-handleBundleDependency",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#handleBundleDependency",
    "method"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#hasdependency",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-method-hasDependency",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#hasDependency",
    "method"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#removedependency",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-method-removeDependency",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#removeDependency",
    "method"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#setbundle",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-method-setBundle",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#setBundle",
    "method"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#sourcefilepath",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-member-sourceFilePath",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#sourceFilePath",
    "member"
  ],
  [
    "src/compilers/browserifycompiler.js~browserifycompiler#targetfilepath",
    "class/src/compilers/BrowserifyCompiler.js~BrowserifyCompiler.html#instance-member-targetFilePath",
    "src/compilers/BrowserifyCompiler.js~BrowserifyCompiler#targetFilePath",
    "member"
  ],
  [
    "src/compilers/coffeescriptcompiler.js",
    "file/src/compilers/CoffeeScriptCompiler.js.html",
    "src/compilers/CoffeeScriptCompiler.js",
    "file"
  ],
  [
    "src/compilers/coffeescriptcompiler.js~babelcodecompiler#compilechunk",
    "class/src/compilers/CoffeeScriptCompiler.js~BabelCodeCompiler.html#instance-method-compileChunk",
    "src/compilers/CoffeeScriptCompiler.js~BabelCodeCompiler#compileChunk",
    "method"
  ],
  [
    "src/compilers/copycompiler.js",
    "file/src/compilers/CopyCompiler.js.html",
    "src/compilers/CopyCompiler.js",
    "file"
  ],
  [
    "src/compilers/copycompiler.js~copycompiler#compilechunk",
    "class/src/compilers/CopyCompiler.js~CopyCompiler.html#instance-method-compileChunk",
    "src/compilers/CopyCompiler.js~CopyCompiler#compileChunk",
    "method"
  ],
  [
    "src/compilers/lesscompiler.js",
    "file/src/compilers/LessCompiler.js.html",
    "src/compilers/LessCompiler.js",
    "file"
  ],
  [
    "src/compilers/lesscompiler.js~lesscompiler#compilechunk",
    "class/src/compilers/LessCompiler.js~LessCompiler.html#instance-method-compileChunk",
    "src/compilers/LessCompiler.js~LessCompiler#compileChunk",
    "method"
  ],
  [
    "src/compilers/livescriptcompiler.js",
    "file/src/compilers/LiveScriptCompiler.js.html",
    "src/compilers/LiveScriptCompiler.js",
    "file"
  ],
  [
    "src/compilers/livescriptcompiler.js~livescriptcompiler#compilechunk",
    "class/src/compilers/LiveScriptCompiler.js~LiveScriptCompiler.html#instance-method-compileChunk",
    "src/compilers/LiveScriptCompiler.js~LiveScriptCompiler#compileChunk",
    "method"
  ],
  [
    "src/compilers/styluscompiler.js",
    "file/src/compilers/StylusCompiler.js.html",
    "src/compilers/StylusCompiler.js",
    "file"
  ],
  [
    "src/compilers/styluscompiler.js~styluscompiler#compilechunk",
    "class/src/compilers/StylusCompiler.js~StylusCompiler.html#instance-method-compileChunk",
    "src/compilers/StylusCompiler.js~StylusCompiler#compileChunk",
    "method"
  ],
  [
    "src/compilers/index.js",
    "file/src/compilers/index.js.html",
    "src/compilers/index.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/lib/builder.js",
    "file/src/lib/Builder.js.html",
    "src/lib/Builder.js",
    "file"
  ],
  [
    "src/lib/builder.js~builder#addcompiler",
    "class/src/lib/Builder.js~Builder.html#instance-method-addCompiler",
    "src/lib/Builder.js~Builder#addCompiler",
    "method"
  ],
  [
    "src/lib/builder.js~builder#addtask",
    "class/src/lib/Builder.js~Builder.html#instance-method-addTask",
    "src/lib/Builder.js~Builder#addTask",
    "method"
  ],
  [
    "src/lib/builder.js~builder#addtasks",
    "class/src/lib/Builder.js~Builder.html#instance-method-addTasks",
    "src/lib/Builder.js~Builder#addTasks",
    "method"
  ],
  [
    "src/lib/builder.js~builder#asynctasks",
    "class/src/lib/Builder.js~Builder.html#instance-member-asyncTasks",
    "src/lib/Builder.js~Builder#asyncTasks",
    "member"
  ],
  [
    "src/lib/builder.js~builder#compilers",
    "class/src/lib/Builder.js~Builder.html#instance-member-compilers",
    "src/lib/Builder.js~Builder#compilers",
    "member"
  ],
  [
    "src/lib/builder.js~builder#constructor",
    "class/src/lib/Builder.js~Builder.html#instance-constructor-constructor",
    "src/lib/Builder.js~Builder#constructor",
    "method"
  ],
  [
    "src/lib/builder.js~builder#options",
    "class/src/lib/Builder.js~Builder.html#instance-member-options",
    "src/lib/Builder.js~Builder#options",
    "member"
  ],
  [
    "src/lib/builder.js~builder#removecompiler",
    "class/src/lib/Builder.js~Builder.html#instance-method-removeCompiler",
    "src/lib/Builder.js~Builder#removeCompiler",
    "method"
  ],
  [
    "src/lib/builder.js~builder#start",
    "class/src/lib/Builder.js~Builder.html#instance-method-start",
    "src/lib/Builder.js~Builder#start",
    "method"
  ],
  [
    "src/lib/builder.js~builder#taskinstances",
    "class/src/lib/Builder.js~Builder.html#instance-member-taskInstances",
    "src/lib/Builder.js~Builder#taskInstances",
    "member"
  ],
  [
    "src/lib/builder.js~builder#tasks",
    "class/src/lib/Builder.js~Builder.html#instance-member-tasks",
    "src/lib/Builder.js~Builder#tasks",
    "member"
  ],
  [
    "src/lib/compiletask.js",
    "file/src/lib/CompileTask.js.html",
    "src/lib/CompileTask.js",
    "file"
  ],
  [
    "src/lib/compiletask.js~compiletask#compileallfiles",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-method-compileAllFiles",
    "src/lib/CompileTask.js~CompileTask#compileAllFiles",
    "method"
  ],
  [
    "src/lib/compiletask.js~compiletask#compilefile",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-method-compileFile",
    "src/lib/CompileTask.js~CompileTask#compileFile",
    "method"
  ],
  [
    "src/lib/compiletask.js~compiletask#compiler",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-member-compiler",
    "src/lib/CompileTask.js~CompileTask#compiler",
    "member"
  ],
  [
    "src/lib/compiletask.js~compiletask#constructor",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-constructor-constructor",
    "src/lib/CompileTask.js~CompileTask#constructor",
    "method"
  ],
  [
    "src/lib/compiletask.js~compiletask#ensurefiledirectory",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-method-ensureFileDirectory",
    "src/lib/CompileTask.js~CompileTask#ensureFileDirectory",
    "method"
  ],
  [
    "src/lib/compiletask.js~compiletask#gettargetpath",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-method-getTargetPath",
    "src/lib/CompileTask.js~CompileTask#getTargetPath",
    "method"
  ],
  [
    "src/lib/compiletask.js~compiletask#setcompiler",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-method-setCompiler",
    "src/lib/CompileTask.js~CompileTask#setCompiler",
    "method"
  ],
  [
    "src/lib/compiletask.js~compiletask#sourcedirectorypath",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-member-sourceDirectoryPath",
    "src/lib/CompileTask.js~CompileTask#sourceDirectoryPath",
    "member"
  ],
  [
    "src/lib/compiletask.js~compiletask#sourcefileextension",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-member-sourceFileExtension",
    "src/lib/CompileTask.js~CompileTask#sourceFileExtension",
    "member"
  ],
  [
    "src/lib/compiletask.js~compiletask#sourcefilepathmatchexpression",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-get-sourceFilePathMatchExpression",
    "src/lib/CompileTask.js~CompileTask#sourceFilePathMatchExpression",
    "member"
  ],
  [
    "src/lib/compiletask.js~compiletask#sourcefilepathmatches",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-method-sourceFilePathMatches",
    "src/lib/CompileTask.js~CompileTask#sourceFilePathMatches",
    "method"
  ],
  [
    "src/lib/compiletask.js~compiletask#targetdirectorypath",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-member-targetDirectoryPath",
    "src/lib/CompileTask.js~CompileTask#targetDirectoryPath",
    "member"
  ],
  [
    "src/lib/compiletask.js~compiletask#targetfileextension",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-member-targetFileExtension",
    "src/lib/CompileTask.js~CompileTask#targetFileExtension",
    "member"
  ],
  [
    "src/lib/compiletask.js~compiletask#targetpathreplaceexpression",
    "class/src/lib/CompileTask.js~CompileTask.html#instance-get-targetPathReplaceExpression",
    "src/lib/CompileTask.js~CompileTask#targetPathReplaceExpression",
    "member"
  ],
  [
    "src/lib/compiler.js",
    "file/src/lib/Compiler.js.html",
    "src/lib/Compiler.js",
    "file"
  ],
  [
    "src/lib/compiler.js~compiler#compilechunk",
    "class/src/lib/Compiler.js~Compiler.html#instance-method-compileChunk",
    "src/lib/Compiler.js~Compiler#compileChunk",
    "method"
  ],
  [
    "src/lib/compiler.js~compiler#constructor",
    "class/src/lib/Compiler.js~Compiler.html#instance-constructor-constructor",
    "src/lib/Compiler.js~Compiler#constructor",
    "method"
  ],
  [
    "src/lib/compiler.js~compiler#options",
    "class/src/lib/Compiler.js~Compiler.html#instance-member-options",
    "src/lib/Compiler.js~Compiler#options",
    "member"
  ],
  [
    "src/lib/options.js",
    "file/src/lib/Options.js.html",
    "src/lib/Options.js",
    "file"
  ],
  [
    "src/lib/task.js",
    "file/src/lib/Task.js.html",
    "src/lib/Task.js",
    "file"
  ],
  [
    "src/lib/task.js~task#adddependencies",
    "class/src/lib/Task.js~Task.html#instance-method-addDependencies",
    "src/lib/Task.js~Task#addDependencies",
    "method"
  ],
  [
    "src/lib/task.js~task#adddependency",
    "class/src/lib/Task.js~Task.html#instance-method-addDependency",
    "src/lib/Task.js~Task#addDependency",
    "method"
  ],
  [
    "src/lib/task.js~task#builder",
    "class/src/lib/Task.js~Task.html#instance-member-builder",
    "src/lib/Task.js~Task#builder",
    "member"
  ],
  [
    "src/lib/task.js~task#constructor",
    "class/src/lib/Task.js~Task.html#instance-constructor-constructor",
    "src/lib/Task.js~Task#constructor",
    "method"
  ],
  [
    "src/lib/task.js~task#dependencies",
    "class/src/lib/Task.js~Task.html#instance-member-dependencies",
    "src/lib/Task.js~Task#dependencies",
    "member"
  ],
  [
    "src/lib/task.js~task#options",
    "class/src/lib/Task.js~Task.html#instance-member-options",
    "src/lib/Task.js~Task#options",
    "member"
  ],
  [
    "src/lib/task.js~task#removedependency",
    "class/src/lib/Task.js~Task.html#instance-method-removeDependency",
    "src/lib/Task.js~Task#removeDependency",
    "method"
  ],
  [
    "src/lib/task.js~task#start",
    "class/src/lib/Task.js~Task.html#instance-method-start",
    "src/lib/Task.js~Task#start",
    "method"
  ],
  [
    "src/lib/defaultoptions.js",
    "file/src/lib/defaultOptions.js.html",
    "src/lib/defaultOptions.js",
    "file"
  ],
  [
    "src/lib/getfiles.js",
    "file/src/lib/getFiles.js.html",
    "src/lib/getFiles.js",
    "file"
  ],
  [
    "src/lib/logging.js",
    "file/src/lib/logging.js.html",
    "src/lib/logging.js",
    "file"
  ],
  [
    "src/lib/parseoptions.js",
    "file/src/lib/parseOptions.js.html",
    "src/lib/parseOptions.js",
    "file"
  ],
  [
    "src/tasks/babelcodecompiletask.js",
    "file/src/tasks/BabelCodeCompileTask.js.html",
    "src/tasks/BabelCodeCompileTask.js",
    "file"
  ],
  [
    "src/tasks/babelcodecompiletask.js~babelcodecompiletask#constructor",
    "class/src/tasks/BabelCodeCompileTask.js~BabelCodeCompileTask.html#instance-constructor-constructor",
    "src/tasks/BabelCodeCompileTask.js~BabelCodeCompileTask#constructor",
    "method"
  ],
  [
    "src/tasks/babelcodecompiletask.js~babelcodecompiletask#run",
    "class/src/tasks/BabelCodeCompileTask.js~BabelCodeCompileTask.html#instance-method-run",
    "src/tasks/BabelCodeCompileTask.js~BabelCodeCompileTask#run",
    "method"
  ],
  [
    "src/tasks/browsersyncservertask.js",
    "file/src/tasks/BrowserSyncServerTask.js.html",
    "src/tasks/BrowserSyncServerTask.js",
    "file"
  ],
  [
    "src/tasks/browsersyncservertask.js~browsersyncservertask#constructor",
    "class/src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask.html#instance-constructor-constructor",
    "src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask#constructor",
    "method"
  ],
  [
    "src/tasks/browsersyncservertask.js~browsersyncservertask#paths",
    "class/src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask.html#instance-member-paths",
    "src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask#paths",
    "member"
  ],
  [
    "src/tasks/browsersyncservertask.js~browsersyncservertask#reload",
    "class/src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask.html#instance-method-reload",
    "src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask#reload",
    "method"
  ],
  [
    "src/tasks/browsersyncservertask.js~browsersyncservertask#run",
    "class/src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask.html#instance-method-run",
    "src/tasks/BrowserSyncServerTask.js~BrowserSyncServerTask#run",
    "method"
  ],
  [
    "src/tasks/browserifycompiletask.js",
    "file/src/tasks/BrowserifyCompileTask.js.html",
    "src/tasks/BrowserifyCompileTask.js",
    "file"
  ],
  [
    "src/tasks/browserifycompiletask.js~browserifycompiletask#compilefile",
    "class/src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask.html#instance-method-compileFile",
    "src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask#compileFile",
    "method"
  ],
  [
    "src/tasks/browserifycompiletask.js~browserifycompiletask#constructor",
    "class/src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask.html#instance-constructor-constructor",
    "src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask#constructor",
    "method"
  ],
  [
    "src/tasks/browserifycompiletask.js~browserifycompiletask#gettargetpath",
    "class/src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask.html#instance-method-getTargetPath",
    "src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask#getTargetPath",
    "method"
  ],
  [
    "src/tasks/browserifycompiletask.js~browserifycompiletask#run",
    "class/src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask.html#instance-method-run",
    "src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask#run",
    "method"
  ],
  [
    "src/tasks/browserifycompiletask.js~browserifycompiletask#sourcefilepath",
    "class/src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask.html#instance-member-sourceFilePath",
    "src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask#sourceFilePath",
    "member"
  ],
  [
    "src/tasks/browserifycompiletask.js~browserifycompiletask#sourcefilepathmatches",
    "class/src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask.html#instance-method-sourceFilePathMatches",
    "src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask#sourceFilePathMatches",
    "method"
  ],
  [
    "src/tasks/browserifycompiletask.js~browserifycompiletask#targetfilepath",
    "class/src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask.html#instance-member-targetFilePath",
    "src/tasks/BrowserifyCompileTask.js~BrowserifyCompileTask#targetFilePath",
    "member"
  ],
  [
    "src/tasks/coffeescriptcompiletask.js",
    "file/src/tasks/CoffeeScriptCompileTask.js.html",
    "src/tasks/CoffeeScriptCompileTask.js",
    "file"
  ],
  [
    "src/tasks/coffeescriptcompiletask.js~coffeescriptcompiletask#constructor",
    "class/src/tasks/CoffeeScriptCompileTask.js~CoffeeScriptCompileTask.html#instance-constructor-constructor",
    "src/tasks/CoffeeScriptCompileTask.js~CoffeeScriptCompileTask#constructor",
    "method"
  ],
  [
    "src/tasks/coffeescriptcompiletask.js~coffeescriptcompiletask#run",
    "class/src/tasks/CoffeeScriptCompileTask.js~CoffeeScriptCompileTask.html#instance-method-run",
    "src/tasks/CoffeeScriptCompileTask.js~CoffeeScriptCompileTask#run",
    "method"
  ],
  [
    "src/tasks/copycompiletask.js",
    "file/src/tasks/CopyCompileTask.js.html",
    "src/tasks/CopyCompileTask.js",
    "file"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#compileallfiles",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-method-compileAllFiles",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#compileAllFiles",
    "method"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#constructor",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-constructor-constructor",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#constructor",
    "method"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#doesntmatchothertasksourcefilepath",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-method-doesntMatchOtherTaskSourceFilePath",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#doesntMatchOtherTaskSourceFilePath",
    "method"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#getpaths",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-method-getPaths",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#getPaths",
    "method"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#iscompiletask",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-method-isCompileTask",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#isCompileTask",
    "method"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#isntthistask",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-method-isntThisTask",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#isntThisTask",
    "method"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#othercompiletasks",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-get-otherCompileTasks",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#otherCompileTasks",
    "member"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#run",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-method-run",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#run",
    "method"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#sourcefilepathmatchexpression",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-get-sourceFilePathMatchExpression",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#sourceFilePathMatchExpression",
    "member"
  ],
  [
    "src/tasks/copycompiletask.js~copycompiletask#sourcefilepathmatches",
    "class/src/tasks/CopyCompileTask.js~CopyCompileTask.html#instance-method-sourceFilePathMatches",
    "src/tasks/CopyCompileTask.js~CopyCompileTask#sourceFilePathMatches",
    "method"
  ],
  [
    "src/tasks/directorycleanertask.js",
    "file/src/tasks/DirectoryCleanerTask.js.html",
    "src/tasks/DirectoryCleanerTask.js",
    "file"
  ],
  [
    "src/tasks/directorycleanertask.js~directorycleanertask#constructor",
    "class/src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask.html#instance-constructor-constructor",
    "src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask#constructor",
    "method"
  ],
  [
    "src/tasks/directorycleanertask.js~directorycleanertask#paths",
    "class/src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask.html#instance-member-paths",
    "src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask#paths",
    "member"
  ],
  [
    "src/tasks/directorycleanertask.js~directorycleanertask#removedirectorycontents",
    "class/src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask.html#instance-method-removeDirectoryContents",
    "src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask#removeDirectoryContents",
    "method"
  ],
  [
    "src/tasks/directorycleanertask.js~directorycleanertask#run",
    "class/src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask.html#instance-method-run",
    "src/tasks/DirectoryCleanerTask.js~DirectoryCleanerTask#run",
    "method"
  ],
  [
    "src/tasks/lesscompiletask.js",
    "file/src/tasks/LessCompileTask.js.html",
    "src/tasks/LessCompileTask.js",
    "file"
  ],
  [
    "src/tasks/lesscompiletask.js~lesscompiletask#compilefile",
    "class/src/tasks/LessCompileTask.js~LessCompileTask.html#instance-method-compileFile",
    "src/tasks/LessCompileTask.js~LessCompileTask#compileFile",
    "method"
  ],
  [
    "src/tasks/lesscompiletask.js~lesscompiletask#constructor",
    "class/src/tasks/LessCompileTask.js~LessCompileTask.html#instance-constructor-constructor",
    "src/tasks/LessCompileTask.js~LessCompileTask#constructor",
    "method"
  ],
  [
    "src/tasks/lesscompiletask.js~lesscompiletask#run",
    "class/src/tasks/LessCompileTask.js~LessCompileTask.html#instance-method-run",
    "src/tasks/LessCompileTask.js~LessCompileTask#run",
    "method"
  ],
  [
    "src/tasks/lesscompiletask.js~lesscompiletask#sourcefilepath",
    "class/src/tasks/LessCompileTask.js~LessCompileTask.html#instance-member-sourceFilePath",
    "src/tasks/LessCompileTask.js~LessCompileTask#sourceFilePath",
    "member"
  ],
  [
    "src/tasks/lesscompiletask.js~lesscompiletask#sourcefilepathmatchexpression",
    "class/src/tasks/LessCompileTask.js~LessCompileTask.html#instance-get-sourceFilePathMatchExpression",
    "src/tasks/LessCompileTask.js~LessCompileTask#sourceFilePathMatchExpression",
    "member"
  ],
  [
    "src/tasks/lesscompiletask.js~lesscompiletask#targetfilepath",
    "class/src/tasks/LessCompileTask.js~LessCompileTask.html#instance-member-targetFilePath",
    "src/tasks/LessCompileTask.js~LessCompileTask#targetFilePath",
    "member"
  ],
  [
    "src/tasks/livescriptcompiletask.js",
    "file/src/tasks/LiveScriptCompileTask.js.html",
    "src/tasks/LiveScriptCompileTask.js",
    "file"
  ],
  [
    "src/tasks/livescriptcompiletask.js~livescriptcompiletask#constructor",
    "class/src/tasks/LiveScriptCompileTask.js~LiveScriptCompileTask.html#instance-constructor-constructor",
    "src/tasks/LiveScriptCompileTask.js~LiveScriptCompileTask#constructor",
    "method"
  ],
  [
    "src/tasks/livescriptcompiletask.js~livescriptcompiletask#run",
    "class/src/tasks/LiveScriptCompileTask.js~LiveScriptCompileTask.html#instance-method-run",
    "src/tasks/LiveScriptCompileTask.js~LiveScriptCompileTask#run",
    "method"
  ],
  [
    "src/tasks/servertask.js",
    "file/src/tasks/ServerTask.js.html",
    "src/tasks/ServerTask.js",
    "file"
  ],
  [
    "src/tasks/servertask.js~servertask#addpath",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-method-addPath",
    "src/tasks/ServerTask.js~ServerTask#addPath",
    "method"
  ],
  [
    "src/tasks/servertask.js~servertask#constructor",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-constructor-constructor",
    "src/tasks/ServerTask.js~ServerTask#constructor",
    "method"
  ],
  [
    "src/tasks/servertask.js~servertask#monitors",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-member-monitors",
    "src/tasks/ServerTask.js~ServerTask#monitors",
    "member"
  ],
  [
    "src/tasks/servertask.js~servertask#removepath",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-method-removePath",
    "src/tasks/ServerTask.js~ServerTask#removePath",
    "method"
  ],
  [
    "src/tasks/servertask.js~servertask#restartpath",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-method-restartPath",
    "src/tasks/ServerTask.js~ServerTask#restartPath",
    "method"
  ],
  [
    "src/tasks/servertask.js~servertask#restartserver",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-method-restartServer",
    "src/tasks/ServerTask.js~ServerTask#restartServer",
    "method"
  ],
  [
    "src/tasks/servertask.js~servertask#run",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-method-run",
    "src/tasks/ServerTask.js~ServerTask#run",
    "method"
  ],
  [
    "src/tasks/servertask.js~servertask#sourcedirectorypaths",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-member-sourceDirectoryPaths",
    "src/tasks/ServerTask.js~ServerTask#sourceDirectoryPaths",
    "member"
  ],
  [
    "src/tasks/servertask.js~servertask#sourcefilepathmatches",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-method-sourceFilePathMatches",
    "src/tasks/ServerTask.js~ServerTask#sourceFilePathMatches",
    "method"
  ],
  [
    "src/tasks/servertask.js~servertask#startserver",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-method-startServer",
    "src/tasks/ServerTask.js~ServerTask#startServer",
    "method"
  ],
  [
    "src/tasks/servertask.js~servertask#stopserver",
    "class/src/tasks/ServerTask.js~ServerTask.html#instance-method-stopServer",
    "src/tasks/ServerTask.js~ServerTask#stopServer",
    "method"
  ],
  [
    "src/tasks/styluscompiletask.js",
    "file/src/tasks/StylusCompileTask.js.html",
    "src/tasks/StylusCompileTask.js",
    "file"
  ],
  [
    "src/tasks/styluscompiletask.js~styluscompiletask#compilefile",
    "class/src/tasks/StylusCompileTask.js~StylusCompileTask.html#instance-method-compileFile",
    "src/tasks/StylusCompileTask.js~StylusCompileTask#compileFile",
    "method"
  ],
  [
    "src/tasks/styluscompiletask.js~styluscompiletask#constructor",
    "class/src/tasks/StylusCompileTask.js~StylusCompileTask.html#instance-constructor-constructor",
    "src/tasks/StylusCompileTask.js~StylusCompileTask#constructor",
    "method"
  ],
  [
    "src/tasks/styluscompiletask.js~styluscompiletask#run",
    "class/src/tasks/StylusCompileTask.js~StylusCompileTask.html#instance-method-run",
    "src/tasks/StylusCompileTask.js~StylusCompileTask#run",
    "method"
  ],
  [
    "src/tasks/styluscompiletask.js~styluscompiletask#sourcefilepath",
    "class/src/tasks/StylusCompileTask.js~StylusCompileTask.html#instance-member-sourceFilePath",
    "src/tasks/StylusCompileTask.js~StylusCompileTask#sourceFilePath",
    "member"
  ],
  [
    "src/tasks/styluscompiletask.js~styluscompiletask#sourcefilepathmatchexpression",
    "class/src/tasks/StylusCompileTask.js~StylusCompileTask.html#instance-get-sourceFilePathMatchExpression",
    "src/tasks/StylusCompileTask.js~StylusCompileTask#sourceFilePathMatchExpression",
    "member"
  ],
  [
    "src/tasks/styluscompiletask.js~styluscompiletask#targetfilepath",
    "class/src/tasks/StylusCompileTask.js~StylusCompileTask.html#instance-member-targetFilePath",
    "src/tasks/StylusCompileTask.js~StylusCompileTask#targetFilePath",
    "member"
  ],
  [
    "src/tasks/testtask.js",
    "file/src/tasks/TestTask.js.html",
    "src/tasks/TestTask.js",
    "file"
  ],
  [
    "src/tasks/testtask.js~testtask#constructor",
    "class/src/tasks/TestTask.js~TestTask.html#instance-constructor-constructor",
    "src/tasks/TestTask.js~TestTask#constructor",
    "method"
  ],
  [
    "src/tasks/testtask.js~testtask#gettestfilespromises",
    "class/src/tasks/TestTask.js~TestTask.html#instance-method-getTestFilesPromises",
    "src/tasks/TestTask.js~TestTask#getTestFilesPromises",
    "method"
  ],
  [
    "src/tasks/testtask.js~testtask#mochaoptions",
    "class/src/tasks/TestTask.js~TestTask.html#instance-member-mochaOptions",
    "src/tasks/TestTask.js~TestTask#mochaOptions",
    "member"
  ],
  [
    "src/tasks/testtask.js~testtask#run",
    "class/src/tasks/TestTask.js~TestTask.html#instance-method-run",
    "src/tasks/TestTask.js~TestTask#run",
    "method"
  ],
  [
    "src/tasks/testtask.js~testtask#runtestdirectory",
    "class/src/tasks/TestTask.js~TestTask.html#instance-method-runTestDirectory",
    "src/tasks/TestTask.js~TestTask#runTestDirectory",
    "method"
  ],
  [
    "src/tasks/testtask.js~testtask#runtests",
    "class/src/tasks/TestTask.js~TestTask.html#instance-method-runTests",
    "src/tasks/TestTask.js~TestTask#runTests",
    "method"
  ],
  [
    "src/tasks/testtask.js~testtask#sourcedirectorypaths",
    "class/src/tasks/TestTask.js~TestTask.html#instance-member-sourceDirectoryPaths",
    "src/tasks/TestTask.js~TestTask#sourceDirectoryPaths",
    "member"
  ],
  [
    "src/tasks/testtask.js~testtask#watchdirectorypaths",
    "class/src/tasks/TestTask.js~TestTask.html#instance-member-watchDirectoryPaths",
    "src/tasks/TestTask.js~TestTask#watchDirectoryPaths",
    "member"
  ],
  [
    "src/tasks/watchtask.js",
    "file/src/tasks/WatchTask.js.html",
    "src/tasks/WatchTask.js",
    "file"
  ],
  [
    "src/tasks/watchtask.js~watchtask#compilers",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-member-compilers",
    "src/tasks/WatchTask.js~WatchTask#compilers",
    "member"
  ],
  [
    "src/tasks/watchtask.js~watchtask#constructor",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-constructor-constructor",
    "src/tasks/WatchTask.js~WatchTask#constructor",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#getbrowsersynctask",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-getBrowserSyncTask",
    "src/tasks/WatchTask.js~WatchTask#getBrowserSyncTask",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#getcompilertaskforpath",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-getCompilerTaskForPath",
    "src/tasks/WatchTask.js~WatchTask#getCompilerTaskForPath",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#getcompilertasks",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-getCompilerTasks",
    "src/tasks/WatchTask.js~WatchTask#getCompilerTasks",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#getservertask",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-getServerTask",
    "src/tasks/WatchTask.js~WatchTask#getServerTask",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#getservertaskforpath",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-getServerTaskForPath",
    "src/tasks/WatchTask.js~WatchTask#getServerTaskForPath",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#gettesttask",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-getTestTask",
    "src/tasks/WatchTask.js~WatchTask#getTestTask",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#run",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-run",
    "src/tasks/WatchTask.js~WatchTask#run",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#seteventhandlers",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-setEventHandlers",
    "src/tasks/WatchTask.js~WatchTask#setEventHandlers",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#setwatcher",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-method-setWatcher",
    "src/tasks/WatchTask.js~WatchTask#setWatcher",
    "method"
  ],
  [
    "src/tasks/watchtask.js~watchtask#watcher",
    "class/src/tasks/WatchTask.js~WatchTask.html#instance-member-watcher",
    "src/tasks/WatchTask.js~WatchTask#watcher",
    "member"
  ],
  [
    "src/tasks/_plantumlcompile.js",
    "file/src/tasks/_PlantUMLCompile.js.html",
    "src/tasks/_PlantUMLCompile.js",
    "file"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#addclass",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-addClass",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#addClass",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#addclassparent",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-addClassParent",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#addClassParent",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#classes",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-member-classes",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#classes",
    "member"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#compileallfiles",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-compileAllFiles",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#compileAllFiles",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#compilechunk",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-compileChunk",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#compileChunk",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#compilefile",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-compileFile",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#compileFile",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#constructor",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-constructor-constructor",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#constructor",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#convert",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-convert",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#convert",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#doesclassextend",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-doesClassExtend",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#doesClassExtend",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#getclassname",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-getClassName",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#getClassName",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#getclassparent",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-getClassParent",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#getClassParent",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#hasclass",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-hasClass",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#hasClass",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#removeclass",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-removeClass",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#removeClass",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#run",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-run",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#run",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#setclassmethods",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-setClassMethods",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#setClassMethods",
    "method"
  ],
  [
    "src/tasks/_plantumlcompile.js~plantumlcompile#setclassparent",
    "class/src/tasks/_PlantUMLCompile.js~PlantUMLCompile.html#instance-method-setClassParent",
    "src/tasks/_PlantUMLCompile.js~PlantUMLCompile#setClassParent",
    "method"
  ],
  [
    "src/tasks/index.js",
    "file/src/tasks/index.js.html",
    "src/tasks/index.js",
    "file"
  ],
  [
    "src/test/lib/task.js",
    "file/src/test/lib/Task.js.html",
    "src/test/lib/Task.js",
    "file"
  ]
]